---
- name: Deploy Fullstack Application to Kubernetes
  hosts: kubernetes
  become: true

  environment:
    KUBECONFIG: /home/ubuntu/.kube/config

  tasks:

    # ===============================
    # Copier les manifests Kubernetes
    # ===============================
    - name: Copy Kubernetes manifests
      copy:
        src: "{{ playbook_dir }}/"
        dest: /home/ubuntu/k8s-manifests/
        mode: '0755'

    # ===============================
    # Namespace
    # ===============================
    - name: Create namespace
      command: kubectl apply -f /home/ubuntu/k8s-manifests/namespace.yaml

    # ===============================
    # Database
    # ===============================
    - name: Deploy MySQL Secret
      command: kubectl apply -f /home/ubuntu/k8s-manifests/database/mysql-secret.yaml

    - name: Deploy MySQL Storage
      command: kubectl apply -f /home/ubuntu/k8s-manifests/database/mysql-storage.yaml

    - name: Deploy MySQL Deployment
      command: kubectl apply -f /home/ubuntu/k8s-manifests/database/mysql-deployment.yaml

    - name: Wait MySQL Ready
      command: kubectl rollout status deployment/mysql --timeout=120s -n my-app

    # ===============================
    # Backend
    # ===============================
    - name: Deploy Backend
      command: kubectl apply -f /home/ubuntu/k8s-manifests/backend-souhir/backenddeploy.yaml

    - name: Wait Backend Ready
      command: kubectl rollout status deployment/backend-deployment --timeout=120s -n my-app

    # ===============================
    # Frontend
    # ===============================
    - name: Deploy Frontend
      command: kubectl apply -f /home/ubuntu/k8s-manifests/frontend-souhir/frontdeploy.yaml

    - name: Wait Frontend Ready
      command: kubectl rollout status deployment/frontend-deployment --timeout=120s -n my-app

    # ===============================
    # Ingress
    # ===============================
    - name: Deploy Ingress
      command: kubectl apply -f /home/ubuntu/k8s-manifests/ingress.yaml
