############################################
# Deploy Fullstack Application to Kubernetes
############################################

- name: Deploy Fullstack Application to Kubernetes
  hosts: kubernete
  become: true

  environment:
    KUBECONFIG: /var/lib/jenkins/.kube/config

  vars:
    kubeconfig_path: "{{ lookup('env','KUBECONFIG') }}"
    namespace_file: "namespace.yaml"
    db_path: "database"
    backend_path: "backend-souhir"
    frontend_path: "frontend-souhir"
    ingress_file: "ingress.yaml"
    image_tag: "{{ image_tag }}"

  tasks:

    ###################################
    # Namespace
    ###################################
    - name: Apply Namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: "{{ namespace_file }}"

    ###################################
    # Database
    ###################################
    - name: Apply MySQL Secret
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: "{{ db_path }}/mysql-secret.yaml"

    - name: Apply MySQL Storage
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: "{{ db_path }}/mysql-storage.yaml"

    - name: Apply MySQL Deployment
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: "{{ db_path }}/mysql-deployment.yaml"

    ###################################
    # Backend (uses image_tag)
    ###################################
    - name: Deploy Backend
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition: "{{ lookup('template', backend_path + '/backenddeploy.yaml') }}"

    ###################################
    # Frontend (uses image_tag)
    ###################################
    - name: Deploy Frontend
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition: "{{ lookup('template', frontend_path + '/frontdeploy.yaml') }}"

    ###################################
    # Ingress
    ###################################
    - name: Apply Ingress
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: "{{ ingress_file }}"
