---
- name: Deploy Fullstack Application to Kubernetes
  hosts: localhost
  become: false
  vars:
    kubeconfig_path: "{{ lookup('env','KUBECONFIG') }}"
    namespace_file: "namespace.yaml"
    db_path: "database"
    backend_path: "backend-souhir"
    frontend_path: "frontend-souhir"
    ingress_file: "ingress.yaml"

  tasks:

    - name: Apply Namespace
      community.kubernetes.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: "{{ namespace_file }}"

    # Database
    - name: Apply MySQL Secret
      community.kubernetes.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: "{{ db_path }}/mysql-secret.yaml"

    - name: Apply MySQL Storage
      community.kubernetes.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: "{{ db_path }}/mysql-storage.yaml"

    - name: Apply MySQL Deployment
      community.kubernetes.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: "{{ db_path }}/mysql-deployment.yaml"

    # Backend
    - name: Apply Backend Deployment
      community.kubernetes.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: "{{ backend_path }}/backenddeploy.yaml"

    # Frontend
    - name: Apply Frontend Deployment
      community.kubernetes.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: "{{ frontend_path }}/frontdeploy.yaml"

    # Ingress
    - name: Apply Ingress
      community.kubernetes.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: "{{ ingress_file }}"
