apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress
  namespace: my-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: myapp.local
      http:
        paths:
          # Toutes les routes /api/... vont vers le backend
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: backendsvc
                port:
                  number: 8080

          # Tout le reste va vers le frontend
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: frontsvc
                port:
                  number: 80
