---
- name: Build and Push Backend Image
  hosts: localhost
  become: true

  vars:
    image_name: "{{ dockerhub_user }}/backend"
    # Tag unique basé sur le BUILD_NUMBER, sinon 'latest'
    image_tag: "{{ lookup('env','BUILD_NUMBER') | default('latest') }}"
    project_path: "./backend-souhir"
    container_name: backend-container

  tasks:

    - name: Stop and remove backend container if it exists
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
        force_kill: true

    - name: Login to DockerHub
      community.docker.docker_login:
        username: "{{ dockerhub_user }}"
        password: "{{ dockerhub_password }}"

    - name: Pull existing backend image from DockerHub (if any)
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        source: pull
      ignore_errors: true   # continue même si l'image n'existe pas encore

    - name: Build backend image
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        source: build
        force_source: true
        build:
          path: "{{ project_path }}"
        push: true

    - name: Tag backend image as latest
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: latest
        source: local
        push: true

    - name: Logout Docker
      community.docker.docker_login:
        state: absent
