apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: my-app
spec:
  replicas: 1               # Nombre de pods à maintenir en fonctionnement
  revisionHistoryLimit: 2    # Nombre de révisions conservées pour rollback
  strategy:
    type: RollingUpdate       # Stratégie de mise à jour progressive
    rollingUpdate:
      maxUnavailable: 0      # Aucun pod existant ne doit être indisponible pendant la mise à jour
      maxSurge: 1           # Kubernetes peut créer 1 pod supplémentaire temporairement pendant la mise à jour
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: souhirks/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysqlsvc:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: SPRING_PROFILES_ACTIVE
              value: prod
---
apiVersion: v1
kind: Service
metadata:
  name: backendsvc          # nom du service visible par Prometheus
  namespace: my-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
