server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Toutes les requêtes vers Angular
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Servir correctement les fichiers statiques JS, CSS, images
    location ~* \.(?:js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        root /usr/share/nginx/html;
        access_log off;
        log_not_found off;
        expires 1y;
    }
}
