apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      # Init container pour attendre Backend
      initContainers:
        - name: wait-for-backend
          image: busybox:1.34
          command: ['sh', '-c', 'until nc -z backend 8080; do echo waiting for backend; sleep 3; done;']
      containers:
        - name: front
          image: souhirks/frontend:latest
          ports:
            - containerPort: 4200
          env:
            - name: BACKEND_URL
              value: http://backend.my-app.svc.cluster.local:8080
          readinessProbe:
            httpGet:
              path: /
              port: 4200
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 4200
            initialDelaySeconds: 60
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: my-app
spec:
  selector:
    app: front
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
