apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: souhirks/frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_URL
              value: http://backend.my-app.svc.cluster.local:8080

---
apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: my-app
spec:
  selector:
    app: front
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31824
  type: NodePort
